### ISSUE TITLE
Refactor code

### ISSUE THREAD

**Issue by Alexey-T** [mom1/PasteAsString#1]
I want port to CudaText app; so can u make refactor? add file .py with  

```
def make_string(text, syntax)
```

syntax can be 'ruby', 'c++'...; text is entire text block (which is in Clipboard).

**Comment by mom1** [comment]
1. Что он должен возвращать?
2. Еще настройки нужны, их как портировать?

**Comment by Alexey-T** [comment]
возвращать можно или list of string или текст (\n-separated).
2. Их можно как парам-р make_str(text, syntax, ops)

ops = {"tab_size": 4, "dddd": 10 }

**Comment by mom1** [comment]
ок к концу недели

**Comment by mom1** [comment]
Вроде сделал. Глянь пойдет?

**Comment by Alexey-T** [comment]
Не окей, неопнятно что значат пар-ры (последние 2)
И что значат ключи scope
Плис, doc  string

**Comment by Alexey-T** [comment]
понял что len_bef_symbol -- indent_for_1st_line.

**Comment by mom1** [comment]
Примеры настроек [тут](https://github.com/mom1/PasteAsString/blob/master/PasteAsString.sublime-settings)

**Comment by Alexey-T** [comment]
Стало понятней
